### ISSUE TITLE
Any plans for 1.10.2

### ISSUE THREAD

**Issue by marvin-bitterlich** [CannibalVox/McDiscord#14]
It would be cool to use this mod in 1.10.2, are there any plans to update?

**Comment by Towsty** [comment]
Checkout DiscordIntegration on curse.

**Comment by marvin-bitterlich** [comment]
@Towsty That is not what this mod is doing.

**Comment by Towsty** [comment]
Apologies, last time I used this, which was a while back now, I only remember them showing how many people were on line in your discord server through minecraft and had plans for implementing a chat stream.

**Comment by marvin-bitterlich** [comment]
DiscordIntegration is purely Server side and maps discord chat to to mc chat.

McDiscord is also client side and has a nice little button you can see how many people are online and click on it to bring you to the discord channel. It was just nice looking and easy for players to grasp where the other chat thing came from.

We currently announce a join link regularly, but a join button would be better.

**Comment by Towsty** [comment]
Ah, makes sense. My servers population does not fluctuate much so I've never thought about the usefulness of that.

**Comment by marvin-bitterlich** [comment]
Thanks for the recommendation anyways, that mod looks better then the discord mod I currently use to link mc to a channel. Will make sure to check that out.
