### ISSUE TITLE
Error pulling server from Discord

### ISSUE THREAD

**Issue by CompeteToDefeat** [CannibalVox/McDiscord#8]
After updating 2.0.0 the previous issue pulling guilds cleared up and all seemed well, then it appears Discord updated again and now I get the following error at regular intervals.

http://paste.ubuntu.com/12804510/

**Comment by CannibalVox** [comment]
Is this sitll happening?  Didn't repro when I tested it earlier tonight.

**Comment by CompeteToDefeat** [comment]
I looked in the logs from last night and there was a long period where it didn't happen. Then I restarted the server this morning at around 9AM and it happened again shortly afterward but now I haven't seen it again in the last hour since then.

**Comment by CompeteToDefeat** [comment]
Nevermind, just caught it again in the console while I was sitting here playing.

**Comment by CannibalVox** [comment]
We can't control if discords API has timeouts.
